# Generated by Django 4.2.25 on 2025-10-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
